from rpg.sprite import *
from rpg.actor import *
from rpg.game import new_actor

Grunt = new_actor('Grunt', category='enemy', damage=10, hp=10, strange=5, wizdom=10, name='Grunt',
                  states={'down': Animation(
                      ['images/Grunt_0_0.png', 'images/Grunt_0_1.png', 'images/Grunt_0_2.png', 'images/Grunt_0_3.png',
                       'images/Grunt_0_4.png']),
'down_attack': Animation(
                     ['images/Grunt_0_5.png', 'images/Grunt_0_6.png', 'images/Grunt_0_7.png', 'images/Grunt_0_8.png']),
                          'down_right': Animation(['images/Grunt_1_0.png', 'images/Grunt_1_1.png', 'images/Grunt_1_2.png',
                                                   'images/Grunt_1_3.png', 'images/Grunt_1_4.png']),
'down_right_attack': Animation(['images/Grunt_1_5.png', 'images/Grunt_1_6.png', 'images/Grunt_1_7.png',
                                                  'images/Grunt_1_8.png']),
                          'right': Animation(['images/Grunt_2_0.png', 'images/Grunt_2_1.png', 'images/Grunt_2_2.png',
                                              'images/Grunt_2_3.png', 'images/Grunt_2_4.png']),
'right_attack': Animation(['images/Grunt_2_5.png', 'images/Grunt_2_6.png', 'images/Grunt_2_7.png',
                                             'images/Grunt_2_8.png']),
                          'up_right': Animation(['images/Grunt_3_0.png', 'images/Grunt_3_1.png', 'images/Grunt_3_2.png',
                                                 'images/Grunt_3_3.png', 'images/Grunt_3_4.png']),
'up_right_attack': Animation(['images/Grunt_5_0.png', 'images/Grunt_3_6.png', 'images/Grunt_3_7.png',
                                                'images/Grunt_3_8.png']),
                          'up': Animation(['images/Grunt_4_0.png', 'images/Grunt_4_1.png', 'images/Grunt_4_2.png',
                                           'images/Grunt_4_3.png', 'images/Grunt_4_4.png']),
'up_attack': Animation(['images/Grunt_4_5.png', 'images/Grunt_4_6.png', 'images/Grunt_4_7.png',
                                          'images/Grunt_4_8.png']),
                          'down_left': Animation(['images/Grunt_5_0.png', 'images/Grunt_5_1.png', 'images/Grunt_5_2.png',
                                                  'images/Grunt_5_3.png', 'images/Grunt_5_4.png']),
'down_left_attack': Animation(['images/Grunt_5_5.png', 'images/Grunt_5_6.png', 'images/Grunt_5_7.png',
                                                 'images/Grunt_5_8.png']),
                          'left': Animation(['images/Grunt_6_0.png', 'images/Grunt_6_1.png', 'images/Grunt_6_2.png',
                                             'images/Grunt_6_3.png', 'images/Grunt_6_4.png']),
'left_attack': Animation(['images/Grunt_6_5.png', 'images/Grunt_6_6.png', 'images/Grunt_6_7.png',
                                            'images/Grunt_6_8.png']),
                          'up_left': Animation(['images/Grunt_7_0.png', 'images/Grunt_7_1.png', 'images/Grunt_7_2.png',
                                                'images/Grunt_7_3.png', 'images/Grunt_7_4.png']),
'up_left_attack': Animation(['images/Grunt_7_5.png', 'images/Grunt_7_6.png', 'images/Grunt_7_7.png',
                                               'images/Grunt_7_8.png']),
                          'death': Animation(['images/Grunt_8_1.png',
                                            'images/Grunt_8_3.png', 'images/Grunt_8_5.png'], False)})
