from rpg.sprite import *
from rpg.adnd_actor import *
from rpg.game import new_actor

Mage = new_actor('Mage', category='pc', damage=10, hp=10, strange=5, wizdom=10, name='Mage',
                 states={'down': Animation(
                     ['images/Mage_0_0.png', 'images/Mage_0_1.png', 'images/Mage_0_2.png', 'images/Mage_0_3.png',
                      'images/Mage_0_4.png']),
                        'down_attack': Animation(
                     ['images/Mage_0_5.png', 'images/Mage_0_6.png', 'images/Mage_0_7.png', 'images/Mage_0_8.png'], False),
                         'down_right': Animation(['images/Mage_1_0.png', 'images/Mage_1_1.png', 'images/Mage_1_2.png',
                                                  'images/Mage_1_3.png', 'images/Mage_1_4.png']),
                         'down_right_attack': Animation(['images/Mage_1_5.png', 'images/Mage_1_6.png', 'images/Mage_1_7.png',
                                                  'images/Mage_1_8.png'], False),
                         'right': Animation(['images/Mage_2_0.png', 'images/Mage_2_1.png', 'images/Mage_2_2.png',
                                             'images/Mage_2_3.png', 'images/Mage_2_4.png']),
                         'right_attack': Animation(['images/Mage_2_5.png', 'images/Mage_2_6.png', 'images/Mage_2_7.png',
                                             'images/Mage_2_8.png'], False),
                         'up_right': Animation(['images/Mage_3_0.png', 'images/Mage_3_1.png', 'images/Mage_3_2.png',
                                                'images/Mage_3_3.png', 'images/Mage_3_4.png']),
                         'up_right_attack': Animation(['images/Mage_5_0.png', 'images/Mage_3_6.png', 'images/Mage_3_7.png',
                                                'images/Mage_3_8.png'], False),
                         'up': Animation(['images/Mage_4_0.png', 'images/Mage_4_1.png', 'images/Mage_4_2.png',
                                          'images/Mage_4_3.png', 'images/Mage_4_4.png']),
                         'up_attack': Animation(['images/Mage_4_5.png', 'images/Mage_4_6.png', 'images/Mage_4_7.png',
                                          'images/Mage_4_8.png'], False),
                         'down_left': Animation(['images/Mage_5_0.png', 'images/Mage_5_1.png', 'images/Mage_5_2.png',
                                                 'images/Mage_5_3.png', 'images/Mage_5_4.png']),
                         'down_left_attack': Animation(['images/Mage_5_5.png', 'images/Mage_5_6.png', 'images/Mage_5_7.png',
                                                 'images/Mage_5_8.png'], False),
                         'left': Animation(['images/Mage_6_0.png', 'images/Mage_6_1.png', 'images/Mage_6_2.png',
                                            'images/Mage_6_3.png', 'images/Mage_6_4.png']),
                         'left_attack': Animation(['images/Mage_6_5.png', 'images/Mage_6_6.png', 'images/Mage_6_7.png',
                                            'images/Mage_6_8.png'], False),
                         'up_left': Animation(['images/Mage_7_0.png', 'images/Mage_7_1.png', 'images/Mage_7_2.png',
                                               'images/Mage_7_3.png', 'images/Mage_7_4.png']),
                         'up_left_attack': Animation(['images/Mage_7_5.png', 'images/Mage_7_6.png', 'images/Mage_7_7.png',
                                               'images/Mage_7_8.png'], False),
                         'death': Animation(['images/Mage_8_0.png', 'images/Mage_8_1.png', 'images/Mage_8_2.png',
                                             'images/Mage_8_3.png', 'images/Mage_8_4.png', 'images/Mage_8_5.png', 'images/Mage_8_6.png'], False)})
